services:
  devhands:
    build:
      context: .
    container_name: devhands_cli
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    stdin_open: true 
    tty: true
    command: poetry run python devhands/main.py

  test:
    build:
      context: .
    container_name: devhands_test
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: poetry run pytest
